CREATE TABLE `STUDENT` (
	`id` SERIAL,
	`NO` VARCHAR(10) NOT NULL,
	`NAME` VARCHAR(10) DEFAULT NULL,
	`ENT_YEAR` INT(10) DEFAULT NULL,
	`CLASS_NUM` CHAR(3) DEFAULT NULL,
	`IS_ATTEND` BOOLEAN DEFAULT NULL,
	`SCHOOL_CD` CHAR(3) DEFAULT NULL,
	PRIMARY KEY (`NO`)
)ENGINE=InnoDB;